/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadorapaneles;

/**
 *
 * @author Adan Sanchez
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        OPsuma = new javax.swing.JMenuItem();
        OPresta = new javax.swing.JMenuItem();
        OPmultiplicacion = new javax.swing.JMenuItem();
        OPdivision = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        OPsalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        jMenu1.setText("OPERACION");

        OPsuma.setText("SUMA");
        OPsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPsumaActionPerformed(evt);
            }
        });
        jMenu1.add(OPsuma);

        OPresta.setText("RESTA");
        OPresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPrestaActionPerformed(evt);
            }
        });
        jMenu1.add(OPresta);

        OPmultiplicacion.setText("MULTIPLICACIÓN");
        OPmultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPmultiplicacionActionPerformed(evt);
            }
        });
        jMenu1.add(OPmultiplicacion);

        OPdivision.setText("DIVISIÓN");
        OPdivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPdivisionActionPerformed(evt);
            }
        });
        jMenu1.add(OPdivision);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("SALIR");

        OPsalir.setText("TERMINAR");
        OPsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPsalirActionPerformed(evt);
            }
        });
        jMenu2.add(OPsalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OPsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPsumaActionPerformed
        // TODO add your handling code here:
        FrmSuma FrmSuma = new FrmSuma();
        FrmSuma.setVisible(true);
        jDesktopPane1.add(FrmSuma);
    }//GEN-LAST:event_OPsumaActionPerformed

    private void OPrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPrestaActionPerformed
        // TODO add your handling code here:
        FrmResta FrmResta = new FrmResta();
        FrmResta.setVisible(true);
        jDesktopPane1.add(FrmResta);
    }//GEN-LAST:event_OPrestaActionPerformed

    private void OPmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPmultiplicacionActionPerformed
        // TODO add your handling code here:
        FrmMultiplicacion FrmMultiplicacion = new FrmMultiplicacion();
        FrmMultiplicacion.setVisible(true);
        jDesktopPane1.add(FrmMultiplicacion);
    }//GEN-LAST:event_OPmultiplicacionActionPerformed

    private void OPdivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPdivisionActionPerformed
        // TODO add your handling code here:
        FrmDivision FrmDivision = new FrmDivision();
        FrmDivision.setVisible(true);
        jDesktopPane1.add(FrmDivision);
    }//GEN-LAST:event_OPdivisionActionPerformed

    private void OPsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPsalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_OPsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem OPdivision;
    private javax.swing.JMenuItem OPmultiplicacion;
    private javax.swing.JMenuItem OPresta;
    private javax.swing.JMenuItem OPsalir;
    private javax.swing.JMenuItem OPsuma;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
